### PR TITLE
 Building with Responsive Design

### PR DESCRIPTION
**Pull request by nellencr**
# Building with Responsive Design
In this project, we made a clone of  [The Next Web](https://thenextweb.com/), putting emphasis on how it responds to different screen sizes.
 We used floats, positions, flex, and grid to create the layout, then we used media queries for its responsiveness.
Here is the [Live Demo](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)

### CODE REVIEW

**Comment by nellencr** [comment]
## Building with Responsive Design 
 We closed the previous pull request because we had stickler issues, but we have : 

- fixed the overlapping elements in the latest news section as requested by the previous TSE and
- fixed the latest deals section to adapt to smaller screen sizes.

Here is the [Live Demo Link](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)
Here also is a link to the [previous TSE's comment](https://github.com/nellencr/TNW-clone/pull/2#issuecomment-588543514)

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi team, you are getting there :arrow_forward:. But there are still issues to fix**
1. The logo now disappears completely on medium screens. This is not so in the original.

2. There is still overlapping in the Latest News section
image

3. On small and medium screens, check the left margin on the sections below the Latest News section. The margin is unnecessarily large as against what is on the original.

### Optional:
1. The image width in this section, should be the same with the div directly below it 
image

2, On medium screens, Latest Deals and Latest News sections are arranged 3 per row

_**Kindly make these changes and submit another code review request.**_

**Cheers:stars:**

**Comment by Temmarie** [comment]
## Building with Responsive Design 
 We have :
- fixed the overlapping elements in the latest news section as requested by the previous TSE 
- fixed the logo to appear on medium screen sizes and 
- removed the excessive margins 

Here is the [Live Demo Link](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)

**Comment by lekegitrepo** [comment]
**Good Job Team!**
You have done **_excellent work_**, the is **_logo fixed_** as required by the previous reviewer but you haven't been able to fix the other two required changes. Let me share with you the images of the medium and small screen has it still remains unfixed:
1. There is still overlapping here.
image

2.  There is still an unnecessary left margin on these sections.
image

**_Make these changes and re-submit for review._**
If you have any doubt or question contact me on slack.

**Reviewed by:** **_Temitayo Adeleke_**
-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
**Status: Required Changes**

**Comment by Temmarie** [comment]
## Building with Responsive Design 
 We have :
- fixed the overlapping elements in the latest news section as requested by the previous TSE and
- removed the excessive margins 

Here is the [Live Demo](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Project looks amazing. Congratulation :+1: Approved.
Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
