### PR TITLE
 Feature Building with Responsive Design

### PR DESCRIPTION
**Pull request by Temmarie**
In this project, we made a clone of  [The Next Web](https://thenextweb.com/), putting emphasis on how it responds to different screen sizes.
 We used floats, positions, flex and grid to create the layout, then we used media queries for its responsiveness.
  Here is a [Live Demo](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team       
#### Great Job so far, but there are a few more things required. 
### General
- [x] For Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.
- [x] Configure the linter well.
##### Navigation bar
###### Large version
* [x] The search icon should be an icon not button 

##### Top 3 articles section

###### Medium version changes
* [x] The TWN logo should disappear when viewed on medium screens

##### Latest Funding section

###### Small version changes

* [x] The elements are overlapping , let's fix that.

##### Latest deals section

###### Small version changes
- [x] The elements are not well positioned, let's fix that.
Yours


Original

##### Footer

###### Small version changes
* [x] It should contain social media icons that are vertically and horizontally aligned ([link to page](https://thenextweb.com/))
#### Yours


#### Original


### Make changes and submit another code review request.
*Happy coding*

**Comment by Temmarie** [comment]
## Building with Responsive Design
Made the site responsive to smaller screens as suggested by the previous TSE by: 
- removing the button from the search icon
- removing comments
- fixing the overlapping elements
- making social media icons vertically and horizontally aligned and
- properly positioning the elements in the latest deals section
Here is a [Live Demo](https://raw.githack.com/nellencr/TNW-clone/feature/index.html)

**Comment by thsvr** [comment]
This project is under review by Thaís Vieira

**Comment by thsvr** [comment]
### Status: changes required


Hi @Temmarie and @nellencr, you are almost done :smiley:  :smiley: 
Your job looks amazing but there are a few changes:

1. On the medium screen, your navbar is crashing. Please fix it. You can notice looking through the original website that the list content can be hidden for medium screens;

medium-nav

2- The content is overlapping the image on the small screen, please fix it:

overlaping-small

3- Please align the image with the text on the small screen:

not-align-small

4- Please fix the footer on the small screen:

footer-small-screen


5- Please don't forget to enable Stickler in this repo before the next code review.

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo]()

**Happy coding and good luck on the next submission** :computer:  

Thaís Vieira (TSE)

**Pull request closed without merging**
